language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest cbrf/tests.py
deploy:
  provider: pypi
  user: egregors
  password:
    secure: fTqNmQ68pJ12/Sc5qk6fDcvw7NqgpRcGfjMVI6kdO5tgO3lQe0lJprylNtwRtJF4iqcfcBwdQ/RrxaIOwRzl4Jw31FSkdq3jp4lH4bLARfFPI0d1Vq/aYoiKnMjty/3U4dUeHLHviiiqukCl5ZJ+XM3WJfLp4xppibIqV0Hb96TylAfU9Zk7PL9Jm+LATX8Mw+Yyec/WmlTiKPGzuv9ukwpvBu2vBOn8SPJoXxjyJbi3gMuFvTmUXtP+3u3MKMTuaDKeq5w156mW2kn76swEHn65Ak4aeAhxHoTKBmYbQikOYq89NYlOSqYrIKtVzE8oR8mRov9aaOpwrQO7ESNEwyQIdhHPTAxyc9ByogYmfaLZdKQdDAPK2n1eUfzUZXFblPvG9DM5rO7S5VBYiax8O5rbGfOd/NN4mNyz7Et2tK5KsmXqKMsrMuzXEEqQV+wKjuly0TxknjeYCDA52k7Izt3ubjCnf3sSVyzPKIWEafYKU7XpjuBoSbCACt1eL4LxPcFL1hq70odOJLj3ltDQZ3DBjCFXjfcjm0JvSWJ8qACFCFriIXpE8b0m01U38/Xzc9cpCP8jhoTuCS7yCDWAYS3R/ge25UGGeQ0AvhW+PVbhYayb47IL8aKVN/PHxJPuzpAya6nBY9Fujidt9Ybfgu/JfRNtBp8Zhge3mjI0Hns=
  on:
    tags: true
    repo: Egregors/cbrf
    all_branches: true
    distributions: sdist bdist_wheel
notifications:
  slack:
    rooms:
      secure: GU+R7cQWnAji55HIy2R+cxeMcOx7AKyUiCLGO2iLG+8Z9nZYLG0WrpmqEn19JXLtyhuyKtBeEJarA8zbMdehj8ZoITJJX2PbWVP08r9YabNpL0AOIq2w5hjMa/kdVI3HALYCC9A+I/kprMmNhWp0AnkpykHFNNJ9qzCsdhK0Q8pt7gfxGbzxYC0Sbr0TFk6fT4d0w0M67sNSeULMsiCgV75XjEz+UGeeUFLmGn1of83QqdKRDNfbhEzGoAWBo4x2z8pxBDuaI/Es4hwexXq2Tf5LSpMNwpdQ8u19PM2mr+K1mK45+VOB5GeO800pn8drPC30eq9am79SbBB2pjsc5k4u/jDQQG2UUTTZyYgSElQl4713ZUKcttYgS6IipNJb5i0FTCvzacjAJVp0sZo2gl9NScMxzvTTIPciNQoRgmO4EEvpe7eFDAnCV9/EKL6P+AewmbWcULcPpln5SI75s37fBXOWdnP20RaKay//hayMnTHMB2/9npBedJB/rkvfRvLpMU2C+tw8oGXP1yMSrd+Zaygl1IKZTbca5A9OZacAeiekSbYLUJ0kkMOH3YKIPJV6WpPEZ7PWVYd/gVLsCfdfB2Ld3cg2k8cHeQ0+QNN3rlU4eZ1m5NghjeTQxVxHDTPnZ1jtQFrW8JjXOaBiTB9qYCmSCbUWt1asKCwoXRM=
