language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest cbrf/tests.py
deploy:
  provider: pypi
  user: egregors
  password:
    secure: GBTMfKqvGRiYVuLhf6lr94UlvL+msYpav8m9AtF7Eryqtj59+OxIwiVbMWUGnHCcKgeg7N/Q9SU59QKxOiJi01CHVqRpw8xl5Op66wh5IePJ2Yq0rVOtH7E++AOusWTmD1omEpIHlO6CToCxNu63xQKEALZ4vxhKNr2Q/j6TkWyZJl33NDGa1B6V3xhslIWKUUXGvKiuaDIM57DLnIXIIcaE2zB2qMo03TT5bbHiciJJAr+w2TJstHkJ8xCHWLXWF70sBqnQu3MpwzN+/jaeSYg9wKpJ34diN6cB07ufKI8eNxso1vXPKrmPnybZD+E7dDqWJYp2yw4nC2nlI4YUX24RzfTSEhM+hMkqiZUy8urn+9jAsk05vazhgaZXskKv4h1VuxK42Ex60w3kt0LnGF2MIrTyTse/6pAyi/d5xe61l4deb9WqyZER7KoYQwbImRAURFQQChgu7Tzbu+K0/9JvI/dwWYFNUKQLhkltJi9rHmvhp9I156zB1U12OqwpU3lNxfdp7cdKbjzfp3sl206oQgluOICFmx2GgiDgTS1PsoFBKsYFsea4edke+kmY6qSdPYXdGl84RcNHLKhCytOc54P6DYb74Nh9QyoWjnTyf1FQNAWOF0uajBE6szYDsEOK1KoWLeCjBJOmm4P++ppHwhR3mP9IVqO2dmIVH58=
  on:
    tags: true
    all_branches: true
